apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxid-gateway-manager
  namespace: oxid-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxid-gateway-manager
  template:
    metadata:
      labels:
        app: oxid-gateway-manager
    spec:
      containers:
        - name: oxid-gateway-manager
          image: oxid-gateway-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_KEYCLOAK_ID
              value: oxid-gateway-admin
            - name: AUTH_KEYCLOAK_SECRET
              value: 3rxapQwLdkvHiCUksAiHZpkBBxH40XiR
            - name: AUTH_KEYCLOAK_ISSUER
              value: http://localhost:9000/realms/oxid-gateway
            - name: AUTH_SECRET
              value: nEH0DT0mDucfWTlWFndgtuosM9PID1dMq8GR1NKnFok=
            - name: ADMIN_API_URL
              value: http://oxid-gateway-admin-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: oxid-gateway-manager-service
  namespace: oxid-gateway
  labels:
    app: oxid-gateway-manager
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: oxid-gateway-manager
  type: LoadBalancer
